# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# English (default)
en:
  languageCode: en-us
  contentDir: content/en
  languageName: English
  weight: 1
  title: Matteo Sissa
  menu:
    main:
      - name: Home
        url: /
        weight: 10
      - name: Experience
        url: /#experience
        weight: 20
      - name: Skills
        url: /#skills
        weight: 30
      - name: Projects
        url: /#projects
        weight: 40

# Italian
it:
  languageCode: it-it
  contentDir: content/it
  languageName: Italiano
  weight: 2
  title: Matteo Sissa
  menu:
    main:
      - name: Home
        url: /
        weight: 10
      - name: Esperienza
        url: /#experience
        weight: 20
      - name: Competenze
        url: /#skills
        weight: 30
      - name: Progetti
        url: /#projects
        weight: 40

# Spanish
es:
  languageCode: es-es
  contentDir: content/es
  languageName: Español
  weight: 3
  title: Matteo Sissa
  menu:
    main:
      - name: Inicio
        url: /
        weight: 10
      - name: Experiencia
        url: /#experience
        weight: 20
      - name: Competencias
        url: /#skills
        weight: 30
      - name: Proyectos
        url: /#projects
        weight: 40

